packages:
  all:
    providers:
      mpi: [mpich]
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.0.7
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.8.0
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.81.0+gssapi+ldap+nghttp2
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.8
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.8.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.38
      prefix: /usr
  git:
    externals:
    - spec: git@2.34.1~tcltk
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.22.1
      prefix: /usr
  fmt:
    externals:
    - spec: fmt@8.1.1
      prefix: /usr
  json-c:
    externals:
    - spec: json-c@0.15
      prefix: /usr
  mpich:
    externals:
    - spec: mpich@4.0
      prefix: /usr
  nlohmann-json:
    externals:
    - spec: nlohmann-json@3.10
      prefix: /usr
  spdlog:
    externals:
    - spec: spdlog@1.9.2
      prefix: /usr
  tclap:
    externals:
    - spec: tclap@1.2.5
      prefix: /usr
  libfabric:
    variants: fabrics=tcp,rxm
  mercury:
    variants: ~boostsys ~checksum
